ShoppingCart/ShoppingCart/ShoppingCart/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShoppingCart.Models;
using System.Data.Entity;

namespace ShoppingCart.Controllers
{
    public class ShopController : Controller
    {

        // Default Shop page controller method.
        public ActionResult Index(string productCategory, string searchString)
        {
            // Open the database.
            using (ProductsEntities database = new ProductsEntities())
            {
                // Create the category list for the dropdown list and send it to the view.
                var catList = new List<string>();
                var catQry = from d in database.Categories
                             orderby d.Title
                             select d.Title;

                // Select only distinct categories, so there will only be one of each category in the list.
                catList.AddRange(catQry.Distinct());

                // Send the category list to the view.
                ViewBag.productCategory = new SelectList(catList);

                // Select all the products.
                var products = from p in database.Products
                               select p;

                // Select products that match the search string.
                if (!String.IsNullOrEmpty(searchString))
                {
                    products = products.Where(p => p.Title.Contains(searchString));
                }

                // Convert the selected category string to an int usable in the category match query.
                int intCat = 0;

                var catsToInt = from c in database.Categories
                                select c;

                // Loop through all the categories and set the integer eauivalent of the category name.
                foreach (var catToInt in catsToInt)
                {
                    if (productCategory == catToInt.Title)
                    {
                        intCat = catToInt.CategoryID;
                    }
                }


                // Select the matched category integer.
                if (intCat != 0)
                {
                    products = products.Where(x => x.CategoryID == intCat);
                }

                // Convert the query to an IEnumerable object for eager loading.
                var converted = products.Include("Category").ToList();

                return View(converted);
            }
        }


        // Controller method to use Ajax to update the quantity of a product in the cart without having to reload the page.
        [HttpPost]
        public string UpdateQTY()
        {
            using (ProductsEntities database = new ProductsEntities())
            {
                // Updates the QTY of product in cart from the "cart" session variable.
                // Occurs on page load.

                // Get the POSTED value of the product ID.
                var id = Convert.ToInt32(Request["qtyID"]);

                // Find the matching product.
                Product product = database.Products.Find(id);

                // Check if the Cart exists.
                if (Session["cart"] != null)
                {
                    // Check if the cart contains the requested product.
                    if (((Dictionary<Product, int>)Session["cart"]).ContainsKey(product))
                    {
                        // Return a string representation of the product to the view 
                        // so the quantity of the product in the cart can be set.
                        return ((Dictionary<Product, int>)Session["cart"])[product].ToString();
                    }
                }

                // If there was no product found in the cart (zero quantity), return string value of zero.
                return "0";
            }
        }
    }

}

ShoppingCart/ShoppingCart/ShoppingCart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Shopping Cart App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shopping Cart App", "Index", "Shop", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Shop", "Index", "Shop")</li>
                    <li>@Html.ActionLink("Cart", "Index", "Cart")</li>
                    <li>@Html.ActionLink("Checkout", "Index", "Checkout")</li>
                </ul>
                @Html.Partial("_Login")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WDT Team</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShoppingCart/ShoppingCart/ShoppingCart/Views/Shared/_Login.cshtml
<ul class="nav navbar-nav navbar-right">
    @if (Session["Username"] == null)
    {
        <li>@Html.ActionLink("Register", "RegisterUser", "Home", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        <li>@Html.ActionLink("Log in", "Login", "Home", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
    }
    else
    {
        <li>@Html.ActionLink("Log out", "Logout", "Home", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
    }
</ul>